# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Add Lib Usb
      if: runner.os == 'macOS'
      shell: bash
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" for package in $(brew ls) do echo $package; brew unlink $package; brew link $package done

    - name: Install macOS PortAudio dependencies
      if: runner.os == 'macOS'
      shell: bash
      run: brew install portaudio

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
