# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.0'

    - name: Install macOS PortAudio dependencies
      if: runner.os == 'macOS'
      shell: bash
      run: brew install portaudio

    - name: Install Libusb dependencies
      if: runner.os == 'macOS'
      shell: bash
      run: brew install libusb; brew install pkg-config; export PKG_CONFIG_PATH="$(brew --prefix libusb)/lib/pkgconfig"

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
